# Generated by Django 3.1.6 on 2021-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210308_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_encode',
            field=models.FileField(blank=True, upload_to='face_encodes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
