# Generated by Django 3.1.6 on 2021-03-17 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_request',
            field=models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
