# Generated by Django 3.1.7 on 2021-04-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210412_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='face_encode',
        ),
    ]
