# Generated by Django 3.1.7 on 2021-04-19 09:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_face_encode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_encode',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
    ]
