# Generated by Django 3.1.6 on 2021-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.CharField(default='B2', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='room',
            field=models.IntegerField(default=43),
        ),
    ]
