# Generated by Django 3.1.6 on 2021-02-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auth',
            new_name='author',
        ),
    ]
