# Generated by Django 3.1.6 on 2021-03-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210311_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
