# Generated by Django 3.1.7 on 2021-03-13 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quesans', '0004_auto_20210223_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
