# Generated by Django 3.1.7 on 2021-03-17 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quesans', '0006_auto_20210315_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvote',
            field=models.ManyToManyField(related_name='downvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
