# Generated by Django 3.1.7 on 2021-04-20 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quesans', '0009_auto_20210413_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.ManyToManyField(related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
