# Generated by Django 3.1.6 on 2021-04-23 09:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quesans', '0011_auto_20210420_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='desc'),
        ),
    ]
