# Generated by Django 3.1.6 on 2021-04-23 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quesans', '0013_auto_20210423_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bookmarked',
        ),
        migrations.AddField(
            model_name='question',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
