# Generated by Django 3.1.6 on 2021-05-12 09:25

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quesans', '0014_auto_20210423_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Image'),
        ),
    ]
